apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules
  namespace: monitoring
spec:
  groups:
  - name: kubernetes
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) by (pod) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage detected
        description: Pod {{ $labels.pod }} has high CPU usage

    - alert: HighMemoryUsage
      expr: sum(container_memory_usage_bytes{container!=""}) by (pod) / sum(container_spec_memory_limit_bytes{container!=""}) by (pod) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        description: Pod {{ $labels.pod }} has high memory usage

    - alert: PodRestarting
      expr: increase(kube_pod_container_status_restarts_total[1h]) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Pod is restarting
        description: Pod {{ $labels.pod }} has restarted 