apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: trading
    user: postgres
    secureJsonData:
      password: postgres123
    editable: false
    version: 1

  - name: Kafka
    type: prometheus
    access: proxy
    url: http://kafka-exporter:9308
    editable: false
    version: 1
