groups:
  - name: trading_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(trade_processing_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate in trade processing
          description: 'Error rate is {{ $value }} per second'

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(trade_processing_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High latency in trade processing
          description: '95th percentile latency is {{ $value }} seconds'

      - alert: KafkaConsumerLag
        expr: kafka_consumer_lag > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High Kafka consumer lag
          description: 'Consumer lag is {{ $value }} messages'

      - alert: DatabaseErrors
        expr: rate(db_connection_errors_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Database connection errors
          description: '{{ $value }} database errors per second'

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service is down
          description: 'Service {{ $labels.job }} is down'
